export default {
    //Common//
    cancel: 'Cancelar',
    categories: 'Categorias',
    category: 'Categoria',
    date: 'Fecha',
    delete: 'Eliminar',
    downloads: 'Descargas',
    edit: 'Editar',
    edit_mod: 'Editar Mod',
    error: 'Error',
    last_updated: 'Ultima Actualizacion',
    by_user_time_ago: '{time} por {user}',
    no_downloads: 'No Files or Links',
    not_published: 'Not Published',
    upload_mod: 'Subir Mod',
    changelog: 'Lista de Cambios',
    description: 'Descripcion',
    version: 'Version',
    tags: 'Tags',
    filter_out_tags: 'Excluir Tags',
    mods: 'Mods',
    threads: 'Hilos',
    users: 'Usuario',
    report: 'Reportar',
    report_desc: `
Si piensas que {0} esta rompiendo las reglas, puedes reportarlo al equipo de moderacion y lo inspeccionaremos lo antes posible. 
¡Reportes masivos o falsos no seran tolerados!
`,
    submit: 'Enviar',
    images: 'Imagenes',
    type: 'Tipo',
    wiki: 'Wiki',
    discord: 'Discord',
    support_us: 'Soportanos',
    support_mws: 'Soporta ModWorkshop',
    rules: 'Reglas',
    privacy: 'Politica de Privacidad',
    terms: 'Terminos de Servicio',
    about: 'Sobre Nosotros',
    profile: 'Perfil',
    user_settings: 'Configuraciones de Usuario',
    logout: 'Cerrar Sesion',
    game_category: 'Juego/Categoria',
    likes: 'Me gusta',
    load_more: 'Cargar Mas...',
    search: 'Buscar...',
    user: 'Usuarior',
    mod: 'Mod',
    all: 'Todos',
    published_at: 'Fecha de Publicacion',
    return_to_top: 'Volver Arriba',
    search_mods: 'Buscar Mods',
    search_mods_matching: 'Mods Matching "{0}"',
    search_mods_game: '{1} Mods',
    search_mods_game_matching: '{1} Mods Matching "{0}"',
    search_users: 'Buscar Usuarios',
    search_users_matching: 'Users Matching "{0}"',
    search_threads_matching: 'Threads Matching "{0}"',
    search_threads: 'Buscar Hilos',
    search_threads_game: '{1} Threads',
    search_threads_game_matching: '{1} Threads Matching "{0}"',
    comments_disabled: 'Los comentarios han sido deshabilitados; Solo el creador del mod, miembros, y moderadores pueden comentar.',
    popularity: 'Popularidad',
    popular_today: 'Popular Hoy',
    popular_weekly: 'Popular Esta Semana',
    popular_monthly: 'Popular Este Mes',
    banner: 'Banner',
    save: 'Guardar',
    pin: 'Marcar',
    unpin: 'Desmarcar',
    pinned: 'Marcado',
    follow: 'Seguir',
    unfollow: 'Dejar de seguri',
    subscribe: 'Subscribirse',
    unsubscribe: 'De-suscribirse',
    no_bio: 'No tiene Bio.',
    color_blue: 'Azul',
    color_green: 'Verde',
    color_pink: 'Rosa',
    color_red: 'Rojo',
    color_teal: 'Teal',
    color_purple: 'Purpura',
    color_gray: 'Gris',
    color_orange: 'Naranja',
    color_cyan: 'Cyan',
    page_error_401: 'Tienes que tener una cuenta para acceder a esta pagina',
    page_error_404: 'Esta pagina no existe',
    page_error_403: 'No tienes permiso para ver esta pagina',
    page_error_403_banned: 'Usuarios bloqueados no pueden ver esta pagina',
    page_error_403_unactivated: 'Usuarios desactivados no pueden ver esta pagina',
    error_500: 'Error de Servidor. Por favor contacte a un administrador',
    error_502: 'No se puede acceder al servidor, Por favor espera e intenta nuevamente.',
    error_suspended: 'Esta Mod esta suspendido y no puede ser accedido.',
    error_rejected: 'This mod has been rejected and cannot be accessed.',
    error_unapproved: 'This mod is waiting for approval. Please check again later.',
    error_409: 'This resource already exists.',
    error_404: 'This resource does not exist. It my have been already deleted.',
    error_403: 'You don\'t have permissions to do this action.',
    error_403_banned: 'Banned users cannot do this action!',
    error_403_unactivated: 'Please activate your account before doing this action!',
    registration_date: 'Fecha de Registracion',
    post: 'Postear',
    back_to_home: 'Volver a Casa',
    unsaved_changes: 'Tienes cambios no guardados',
    latest_mods: 'Ultimos Mods actualizados',
    popular_mods: 'Mods Populares',
    register: 'Registracion',
    login: 'Ingresar',
    views: 'Vistas',
    danger_zone: '¡Danger Zone!',
    nothing_found: 'No se encontro nada que mostrar :/',
    games: 'Juegos',
    news: 'Noticias',
    forum: 'Foros',
    reply: 'Responder',
    replies_n: 'una respuesta | {n} respuestas',
    editing: 'Editando',
    replying: 'Respondiendo',
    read_all_replies: 'Marcar TODAS las respuestas como vistas',
    comments: 'comentarios',
    replies: 'Replies',
    docs: 'Documentos',
    archive: 'Archivos',
    unarchive: 'Des-Archivado',
    lock: 'Bloquear',
    unlock: 'Des-Bloquear',
    dark_theme: 'Tema Oscuro',
    light_theme: 'Tema Claro',
    content_settings: 'COnfiguracion del Contenido',
    remove: 'Remover',
    resource_mod: 'mod',
    resource_thread: 'hilos',
    resource_comment: 'comentar',
    resource_user: 'usuario',
    admin_page: 'Pagina de Administrador',
    discard: 'Descartar',
    never: 'Nunca',
    title: 'Titulo',
    name: 'Nombre',
    view: 'Vistas',
    are_you_sure: '¿Estas seguro?',
    irreversible_action: '¡Esta Accion no se puede deshacer!',
    something_went_wrong: 'Algo fue muy mal',
    not_available: 'N/A',
    no_reason: 'No hay razon describida.',
    upload_date: 'Fecha de Subida',
    actions: 'Acciones',
    order: 'Orden',
    game: 'Juego',
    none: 'Nada',
    any_forum: 'Cualquier Foro',
    any_game: 'Cualquier Juego',
    upload: 'Subir',
    here: 'aqui',
    content: 'Contenido',
    documents: 'Documentos',
    settings: 'Configuraciones',
    supporters: 'Patrocinadores',
    approvals: 'Aprobados',
    bans: 'Bans',
    suspensions: 'Suspensiones',
    reports: 'Reportes',
    forum_categories: 'Categorias del Foro',
    home: 'Casa',
    general: 'General',
    reason: 'Razon',
    active: 'Activo',
    duration: 'Duracion',
    emoji: 'Emoji',
    add: 'Agregar',
    color: 'Color',
    stop: 'Parar',
    file_size: 'Tamaño',
    file_uploader_drop: 'Tire los archivos aqui o haga click en esta area para subirlos',
    uploading: 'Subiendo: {0}%',
    file_name_too_large: 'El Archivo {name} es muy grande!',
    file_name_too_large_max_size: 'El Archivo {name} es muy grande, intenta hacer algo de espacio.',
    failed_upload: 'La subida fallo.',
    write_tab: 'Escribir',
    preview_tab: 'Previsualizar',
    new: 'Nuevo',
    duration_count: 'Contador',
    days: 'Dias',
    weeks: 'Semanas',
    months: 'Meses',
    years: 'Años',
    forever: 'PARA SIEMPRE',
    custom_duration: 'Personalizado',
    close: 'Cerrar',
    hide: 'Esconder',
    random: 'Al Azar',
    welcome_to_mws: '¡Bienvenido a ModWorkshop!',
    mws_short_about: "An open platform that provides the means to create and share mods, tools and ideas for games.",
    expired: 'Expirado',
    select_placeholder: 'Seleccionar...',
    made_with_love: 'Hecho con ❤ por {luffy}',
    operated_by: 'Operado por {company}',
    moments_ago: 'Moments ago',
    browse: 'Browse',
    //Discussions//
    poster: 'Poster',
    last_activity: 'Ultima Actividad',
    last_reply_by: 'Ultima Respuesta por',
    new_thread: 'Nuevo Hilo',
    private_category: 'Categoria de Foros Privados',
    banned_can_post: 'Usuarios Banneados pueden postear (Por Apelaciones)',
    edited: '(Editado)',
    cannot_comment_locked: 'Este Hilo fue bloqueado.',
    cannot_comment_locked_by_mod: 'Este Hilo fue bloqueado por un moderador.',
    cannot_comment_banned: 'Usuarios Banneados no pueden comentar',
    cannot_comment_blocked: 'No puedes responder a este Hilo por que el creador te bloqueo.',
    cannot_comment_blocked_mod: 'No puedes comentar en este Mod por que el creador te bloqueo.',
    announce: 'Anuncio',
    announcement_duration: 'Duracion del Anuncio',
    name_forum: '{name} Foro',
    global_forum: 'Foro Global',
    liked: 'Me Gustas',
    view_all_games: 'Ver todos los Juegos',
    last_updated_games: 'Juegos Actualizados Recientemente',
    delete_comment_desc: 'Esto eliminara el comentario',
    no_threads_found: 'Ningun Hilo fue encontrado',
    return_to_comments: 'Volver a comentarios',
    announcements: 'Anuncios',
    game_announcements: 'Anuncios del Juego',
    no_comments_found: 'No se encontraron Comentarios',
    no_replies_found: 'No se encontraron Respuestas',
    //Mods//
    download: 'Descargas',
    license: 'Licencia',
    show_download_link_warn: 'Ten cuidado con Links sospechosos. Si piensas que un Link es malicioso, por favor reporta el link.',
    show_download_link: 'Mostrar Link de Descarga',
    downloads_alert: 'No Files or Links',
    downloads_alert_desc: 'If a mod does not have files or links, the mod is invisible to the public.',
    share: 'Compartir',
    instructions: 'Instrucciones',
    offsite_mod: 'Mod fuera del sitio.',
    dependencies: 'Dependencias',
    optional: 'Opcional',
    outdated_notice: `⚠ El fuego se ha declarado como des-actualizado! <br>
Este mod puede que no funcione como el autor lo ah intencionado, puede ocasionar crashes y bugs.`,
    transfer_request: `El Autor del Mod a solicitado una transferencia de su pertenencia a la tuya.
Si aceptas, este mod estara bajo tu nombre, incluyendo la responsabilidad de que tu mod se apegue a nuestras reglas.
If the author sent this request to you maliciously, you may decline the request and report the mod or author to the moderators.`,
    downloading_file: 'Descargando Archivo...',
    downloading_file_should: 'La Descarga empezara pronto.',
    downloading_file_help: 'Como Instalar',
    downloading_file_force: 'Forzar Descarga',
    delete_files: 'Eliminar Archivos',
    delete_files_desc: 'This will delete all files of the mod, this cannot be reversed!',
    delete_images: 'Delete Images',
    delete_images_desc: '¡Esto eliminara todas las imagenes del Mod, esto no se puede revertir!',
    short_desc: 'Descripcion Corta',
    short_desc_desc: '¡Un maximo de 150 letras. Sera mostrado en lugares como Discord, y cuando sobrevolando sobre Mods',
    license_cant_choose: '¿No puedes Eleguir?',
    disable_comments: 'Deshabilitar Comentarios',
    transfer_ownership: 'Transferir Pertenencia',
    transfer_mod_warning: `Transferir la Pertenencia de un Mod es peligroso y no puede ser deshecho.
El usuario recibira una invitacion que podra aceptar o negar.
La invitacion expirara en un dia a partir del momento que enviaste la invitacion. Mientras tanto, No podras enviar invitaciones adicionales para el Mod.`,
    thumbnail: 'Thumbnail',
    public: 'Publico',
    unlisted: 'De-listado',
    private: 'Privado',
    hidden: 'Escondido',
    return_to_mod: 'Volver a la Pagina del Mod',
    url: 'URL',
    owner: 'Propietario',
    mod_request: `Has sido invitado para ser parte de los miembros de este Mod con el rol de: {0}.
Si aceptas, podras contribuir al mod y editar su contenido.
Ten en cuenta que, todos los miembros del Mod incluido su creador son responsables del mod tambien.`,
    banner_url_warning: `Los Banners de URL estan siendo discontinuados. Seguira funcionando con Mods antiguos, esperamos que nuevos/actualizados mods
que subna sus banners al sitio de forma correcta. Actual banner URL: {url}
Guardar el mod eliminara el Banner URL!`,
    allowed_size_per_mod: 'Tienes permiso de subiar hasta cantidad {0} de archivos en el mod.',
    mod_desc_help: 'Esta descripcion explica a las personas el proposito de tu mod, es lo primero que veran.',
    primary_download_desc: 'Si tu Mod es una sola descarga, podras eleguir el archivo o link que se usa',
    send_for_approval: 'Enviado para aprobacion',
    send_for_approval_desc: `
Algunos Mods como los de musica, o mods que contengan musica DEBEN SER APROBADOS antes de ser publicados. 
Algunas categorias fuerzan esta opcion.`,
    mod_waiting: 'Este mod esta esperando aprobacion',
    mod_waiting_desc: 'Este mod sera invisible hasta que sea aprobado por un moderador. Asegurate que este mod se apegue a nuestras reglas.',
    mod_rejected: '¡Este mod fue RECHAZADO!',
    mod_rejected_desc: 'Este mod fue rechazado debido a que no se apego a nuestras reglas. Por Ejemplo: No incluir fuentes de la musica, musica con copyright.',
    approve: 'Aprobar',
    reject: 'Rechazar',
    add_offsite_mod: 'Mod Fuera De Sitio',
    add_mod: 'Agregar Mod',
    mod_page: 'Pagina del Mod',
    mod_name_desc: 'Maximum of 150 letters and minimum of 3 letters',
    follow_mod_notifs: 'Follow and get notified for updates',
    main_tab: 'Main',
    downloads_tab: 'Descargas & Actualizaciones',
    images_tab: 'Imagenes',
    members_tab: 'Miembros',
    instructions_tab: 'Dependencias E Instrucciones',
    extra_tab: 'Extra',
    file_doesnt_exist: '¡El archivo no existe!',
    cant_choose_license: '¿No puedes eleguir?',
    delete_mod_desc: 'This will delete the mod and the files associated with it. This action cannot reversed!',
    primary: 'Primario',
    primary_download: 'Descarga Primaria',
    links: 'Links',
    files: 'Archivos',
    edit_file: 'Editar Archivo',
    edit_link: 'Editar Link',
    banner_preview: 'Prevista del Banner',
    thumbnail_preview: 'Previesta de Carta de Thumbnail/Mod',
    no_mods_found: 'No se encontraron Mods :/',
    visibility: 'Visibilidad',
    make_your_mod_discoverable: 'Haz a tus Mods mas faciles de descubrir',
    error_fetching_mods: 'Hubo un error peticionando mods',
    notify_owner_members: 'Notificar Autor y Miembros',
    expires_t: 'Expira en: {time}',
    member_level_collaborator: 'Colaborador',
    member_level_maintainer: 'Manitas',
    member_level: 'Nivel',
    member_accepted: 'Aceptado',
    // Did the user accept the membership request
    member_level_viewer: 'Mirador',
    member_level_contributor: 'Contribuidor',
    allowed_storage: 'Espacio Permitivo (MiB)',
    allowed_storage_help: `Como moderador puedes incrementar el espacio permitivo de este mod a pedido.
Primero deberias recomendar que este entre en la capacidad maxima de espacio disponible si esto no es posible,
Puedes incrementar su espacio hasta 1GiB.`,
    file_type_link: 'Link',
    file_type_file: 'Archivo',
    label: 'Etiqueta',
    edit_member: 'Editar Miembros',
    clear_primary_download: 'Limpiar Descarga Primaria',
    already_sent_transfer: `Has enviando una peticion de transferencia al usuario: {user}
Si quieres transferirlo a otra persona, o cambiaste de idea, cancela tu pedido.
`,
    transfer_keep_as_member: 'Mantener como miembro de Nivel',
    next: 'Next',
    skip: 'Skip',
    go_to_mod_page: 'Go to Mod Page',
    create_and_go: 'Create and Go to Mod Page',
    publish_mod_and_go: 'Publish and Go to Mod Page',
    mod_creation_1: `First things first, let's set-up the basics.`,
    mod_creation_2: `Next, upload some screenshots that show your mod in action ✨`,
    mod_creation_3: `Finally, let's set-up downloads.`,
    publish_mod: 'Publish Mod',
    finish: 'Finish',
    publish_mod_desc: 'Your mod is not published yet. In order for others to see it, it must be published.',
    links_help: 'Click on the plus button to add links',
    upload_file: 'File',
    //User//
    online: 'En Linea',
    offline: 'Offline',
    last_visit: 'Ultima visita',
    block: 'Bloquear',
    unblock: 'Des-Bloquear',
    hide_mods: 'Ocultar Mods',
    unhide_mods: 'Mostrar Mods',
    send_pm: 'Enviar MP',
    roles: 'Roles',
    role: 'Rol',
    game_roles: 'Roles Del Juego',
    supporter_tag: 'Personas que no Soportan ♥',
    password: 'Contraseña',
    current_password: 'Contraseña Actual',
    new_password: 'Contraseña Nueva',
    confirm_password: 'Confirmar Contraseña',
    password_guide: 'La contraseña debe tener como minimo 12 caracteres, contener al menos un digito, una letra en miniscula y mayuscula.',
    change_password: 'Cambiar Contraseña',
    password_error_lowercase: 'La contraseña debe tener una miniscula',
    password_error_uppercase: 'La contraseña debe tener una Mayuscula',
    password_error_digit: 'La contraseña debe tener al menos un digito',
    password_error_match: '¡Las contraseñas deben ser Iguales!',
    sso_only_warning: '¡Ingreso solo de forma Social!',
    sso_only_warning_desc: 'No tienes un E-Mail o contraseña por lo tanto no podras ingresar sin un ingreso social. ¡Te recomendados que te crees un E-mail y contraseña!',
    private_profile_notice: 'Este Perfil es Privado',
    follow_with_notifs: 'Seguir y ser notificado de nuevos Mods',
    support_user: 'Soportar Usuario',
    hiding_mods_view: 'Has escondido los mods del usuario. ¿Quieres ver sus mods?',
    blocked_user_view: 'Has bloqueado al usuario. ¿Quieres ver su perfil?',
    block_user_desc: 'Esto bloqueara todas las formas de comunicacion con el usuario y ocultar sus mods de tu vista',
    hide_user_mods_desc: 'Esto ocultara los mods del Usuario',
    unhide_user_mods_desc: 'This will unhide the user\'s mods',
    connected_accounts_tab: 'Cuentas Conectadas',
    api_access_tab: 'Acceder al API',
    content_tab: 'Contenido',
    account_tab: 'Cuenta',
    avatar: 'Avatar',
    show_tag: 'Mostrars Etiquetas',
    show_tag_desc: 'Esta etiqueta aparece junto a tu nombre. Mayoritariamente usado por moderador y administradores.',
    donation: 'Donacion por URL',
    donation_desc: 'Soportar por PayPal, Ko-Fi, o Comprale un Cafe. Se mostrara en tu perfil y en la pagina de mods.',
    custom_title: 'Titulo Personalizado',
    custom_color: 'Color Customizado',
    custom_color_desc: 'Cambiemos tu color a uno personalizado. Solamente para las personas que nos soportan.',
    private_profile: 'Perfil Privado',
    private_profile_desc: 'Tocar aqui hara tu Perfil Privado. Solo moderadores lo podran ver.',
    invisible: 'Invisible',
    invisible_desc: 'Oculta tu estado online',
    bio: 'Bio',
    bio_desc: 'Habla sobre ti para las personas que miraran tu perfil',
    show_tag_role: 'Etiqueta de Rol',
    show_tag_supporter_or_role: 'Etiqueta de soporte (Rol de respaldo)',
    unique_name: 'Nombre Unico',
    unique_name_desc: 'Un nombre unico para tu perfil y la gente que te menciona',
    display_name: 'Mostrar tu nombre',
    email: 'E-Mail',
    accounts_desc: 'Conecta tu cuenta desde dispositivos compatibles para poder ingresar usandolos.',
    cannot_unlink_desc: '\'Esto des-vinculara tu cuenta de tu  cuenta de Modworkshop y no podras usarla para ingresar aqui nunca mas\'',
    cannot_unlink_reason: 'Para des-vincular tu cuenta primero deber crear un email y contraseña o vincular un servicio diferente.',
    linked_time_ago: 'Vinculado hace {time_ago}',
    link: 'Vincular',
    unlink: 'Des-Vincular',
    unlink_warn: 'Esto des-vinculara tu cuenta de tu  cuenta de Modworkshop y no podras usarla para ingresar aqui nunca mas',
    content_page_info: `
Aqui puedes personalizar el contenido del sitio.
Todo contenido blouqeado no sera mostrado en ningunlar salvo que sea puesto explicitamente.
Contenido que sigas sera mostrado en tu pagina principal.`,
    following: 'Siguiendo',
    blocking: 'Bloqueando',
    followed_mods: 'Mods Seguidos',
    followed_games: 'Juegos Seguidos',
    followed_users: 'Usuarios Seguidos',
    blocked_tags: 'Etiquetas Bloqueadas',
    blocked_users: 'Usuarios Bloqeados',
    block_tag: 'Bloquear Etiqueta',
    login_using_services: 'Ingresa usando',
    register_error_409: '¡El nombre unico que eleguiste no es tan unico!',
    login_error_401: 'El E-Mail o Contraseña ingresado no es correcta',
    login_error_422: 'El E-mail o Contraseña ingrasado es invalida',
    logging_you_in: 'Ingresando. Por favor espere...',
    inactive_account: `Esta cuenta no fue activada todavia. Debemos verificarla a travez de tu direccion de correo electronico.
Cuentas inactivas no pueden realizar la moyoria de las acciones como subir mods o poner comentarios.
Esta cuenta sera automaticamente eliminada si no se registra ninguna accion un dia despues de su creacion.`,
    verifying_email: 'Verificando E-Mail. Espere un momento...',
    verified_email: '¡Cuenta verificada satisfactoriamente! Ahora podras usar tu cuenta.',
    remember_me: 'Recordar',
    linking_account: 'Vinculando cuenta. Espere un momento...',
    done_linking_account: '¡Hecho! Cierra esta pestaña y vuelve a la pestaña anterior.',
    account_already_linked: 'Esta cuenta ya fue vinculada o fue vinculada previamente.',
    mod_count: '{n} Mods',
    customize: 'Personalizar',
    request_my_data: 'Pedir mis datos',
    request_my_data_desc: `Puedes descargar un archivo JSON, que lista todos tus mods, hilos, comentarios, y personas que sigues y bloqueas. 
Esto sera lento.`,
    forgot_password_button: '¿Olvidaste tu contraseña?',
    forgot_password: 'Olvide mi Contraseña',
    already_have_account: 'Already have an account? Sign in here.',
    dont_have_account: 'Don\'t have an account? Create one here.',
    reset_password: 'Resetear Contraseña',
    invalid_user: 'Usuario Invalido',
    api_access_desc: `Los Mods son divertidos y todo, ¿Pero que pasara cuando quieras implementar una forma de actualizar tus mods?¿Y como?
A travez de la API por supuesto!

Genere aqui tu propia API key, generar una nueva API key invalidara la anterior.
`,
    api_access_checkbox: 'Lei los terminos de Servicio detallados {here}.',
    generate_api_key: 'Generar clave de API',
    your_api_key: 'Tu clave de API',
    no_users_found: '¡No se encontraron usuarios!',
    banned: 'Suspendido',
    personal_mods: 'Mods Personales',
    collab_mods: 'Mods Colaborados',
    password_reset_sent: 'El enlace de  tu contraseña reiniciada fue enviada a la direccion de E-Mail de la cuenta asociada a tal.',
    password_reset_sent_unknown: 'Fue enviado satisfactoriamente el enlace para reiniciar tu contraseña a la direccion de E-Mail indicada.',
    send_link: 'Enviar Enlace',
    home_page: 'Pagina Principal',
    game_sections: 'Catalogo de Juegos',
    default_view: 'Vista Por Defecto',
    default_sorting: 'Orden Por Defecto',
    show_mods: 'Mostrar Mods',
    show_threads: 'Mostrar Hilos',
    show_last_updated: 'Mostrar Juegos Actualizados Recientemente',
    are_you_sure_role: 'Are you sure you want give this role? The role is not a vanity role!',
    resend: 'Resend',
    pending_email: 'You\'ve requested to change your email to: {0}. Please check your inbox for the verification link.',
    //Games//
    game_preferences: 'Game Preferences',
    game_buttons: 'Menu de Botones',
    webhook_url: 'Discord Webhook URL',
    short_name: 'Nombre Corto',
    games_hosted: 'Le damos una casita a {n} juegos por ahora.',
    want_your_game: '¿Quieres agregar tu juego favorito? ¿Quieres moderarlo? Haz un pedido aqui {here}',
    //Notifications//
    notification_sub_mod: '{user} puso un comentario en {notifiable}',
    notification_sub_thread: '{user} respodio a {notifiable}',
    notification_sub_comment: '{user} respondio a {notifiable} en {extra}',
    no_alerts_found: 'No se encontraron notificaciones',
    no_more_alerts_found: 'No se consiguieron mas notificacioens',
    notifications: 'Notificationes',
    browse_all_notifications: 'Buscar Todas las Notificaciones',
    mark_all_notifications: 'Marcar Todas las Notificaciones como Leidas',
    delete_seen_notifications: 'Eliminar Notificaciones Vistas',
    delete_all_notifications: 'Eliminar TODAS las Notificaciones',
    notification_transfer_ownership: '{user} a enviado una peticion para transferir el {notifiable} a ti. Presiona aqui para ACEPTAR o RECHAZAR.',
    notification_comment_mention: 'Te ha mencionado en un comentario posteado en {context} por {user}',
    notification_follow_mod_new_version: '{user} lanzo una nueva version de {notifiable}: {extra}',
    notification_mod_suspended: '{notifiable} fue suspendido. Mira la razon en la pagina del mod.',
    notification_mod_unsuspended: '{notifiable} fue de-suspendido.',
    notification_warning: '¡Has recibido una notificacion!',
    mark_as_read: 'Marcar como Leido',
    notification_membership_request: 'Te a invitado a ser un miembro de: {notifiable}',
    notification_mod_rejected: '{notifiable} has been rejected. Please review our rules and ensure your mod abides by it.',
    notification_mod_approved: '{notifiable} has been approved!',
    //Admin//
    ban_error_405: 'El Usuario fue suspendido. Puedes editar su tiempo o de-suspenderlo.',
    warn_user: 'Advertir Usuario',
    cases: 'Casos',
    delete_case_warn: '¿Estas seguro que quieres elimar el caso? Si esto fue un Ban, ¡Des-banea el usuario!',
    can_appeal: 'Puede Apelar (Permitir al usuario publicar en ciertas categorias)',
    case_is_ban: 'Este caso fue suspendido. Eliminarlo cancelara el ban.',
    webhook_url_desc: 'Cuando un mod sea publicado aqui, el sitio llamara a este WebHook (Generalmente Discord)',
    approval_only_desc: 'No importa si un mod o no es subido a esta categoria primero tendra que ser aprobada por un moderador',
    parent_category: 'Categoria Superior',
    url_name: 'Nombre de URL',
    url_name_desc: 'Puede contener caratecteres alfanumericos, como parentesis o guiones.',
    moderation: 'Moderacion',
    suspend: 'Suspender',
    unsuspend: 'De-suspender',
    warn: 'Advertir',
    ban: 'Suspender',
    unban: 'De-Suspender',
    ban_user: 'Suspender Usuario',
    suspended: 'Suspendido',
    mod_suspended: `Este mod fue suspendido y solo sera visible al propietario, como miembros del equipo de moderacion y sus moderadores.
Esta suspension es permanente o temporal, dependiendo de la severidad. Por favor lea {rules}.
Si quieres contactar a un administrador para mas inforacion, o si actualizaste el mod para que este fiel a las reglas, puedes apelar tu suspension aqui {forum}.

Razon de la suspension: "{reason}"`,
    private_threads: 'Hilos Privados',
    role_policies: 'Politicas de Roles',
    game_role_policies: 'Politicas de Rol en el Juego',
    forum_category_can_view: 'Pueden Ver',
    forum_category_can_post: 'Pueden Publicar',
    localized: 'Localizado',
    user_tag: 'Etiqueta',
    user_tag_help: 'Una etiqueta al lado del nombre significa que este usuario es parte de los Moderadores o Administradores.',
    permissions: 'Permisos',
    vanity_role: 'Rol de Vanidad',
    self_assignable_role: 'Self-assignable Role',
    vanity_role_desc: 'Los Roles de vanidad no tienen mas proposito que ser bonitos no tienen ningun permiso.',
    self_assignable_role_desc: 'If the roles can be applied by anyone. Some vanity roles may hold some value and so should not be applied by everyone.',
    members_role_desc: 'Todos los miembros tienen este rol. Solo pueden ser editados por Administradores y no pueden ser eliminados.',
    cant_grant_permission: 'No se puede permitir o denegar permisos que no tienes.',
    tag_notice: 'Avisos',
    tag_notice_desc: 'Una aviso que es puesto encima de lo que publicaste',
    tag_notice_type: 'Tipo de Aviso',
    tag_notice_localized: 'Localizar Aviso',
    tag_notice_info: 'Inform',
    tag_notice_warn: 'Advertencia',
    tag_notice_danger: 'Peligroso',
    game_name_settings: 'Configuraciones del Juego {game}',
    instructions_templates: 'Plantillas de Instrucciones',
    instructions_template: 'Instructions Template',
    upgrade_user: 'Mejorar Usuario',
    upgrade: 'Mejorar',
    could_not_upgrade_user: '\'No se puede mejorar al usuairo. ¿Capaz ya tienen membresia?\'',
    stop_supporter_status: '¿Denegar el estado de soportador al usuario?',
    stop_supporter_status_desc: '¡Solo debes hacer esto si el usuario pidio un rembolso o lo pidio!',
    reported_by: 'Reportado por',
    reported_user: 'Usuario Reportado',
    delete_all_mods: 'Eliminar todos los Mods',
    delete_all_discussions: 'Eliminar TODAS las Discusiones',
    go_to_content: 'Ir al Contenido',
    warn_owner: 'Advertir Usuario',
    issued: 'Entregado',
    expires: 'Expirado',
    delete_category_warning: `¿Estas seguro que quieres eliminar esta categoria? 
Los mods no seran eliminados junto con la categoria, solo no seran parte de ella nunca mas.
Solo has esto si estas 100% SEGURO.
`,
    game_admin_page_desc: 'Esta es la pagina de administracion del juego. Contiene un par de cosas para la administracion del juego.',
    successfully_banned: '¡Usuario Suspendido Satisfactoriamente!',
    //Supporter//
    currently_supported: 'Las personas asombrosas que nos soportඞn   ',
    supporter_after_donating: 'Despues de Donar, contacta a uno de los administradores para que te abrazen.',
    supporter_desc: '¿Quieres soportarnos?',
    supporter_currently: 'Las personas geniales que nos soportඞn',
    supporter_already: 'Yඞ nos ඞyudඞste ♥. ¡Muchisimඞs Graciඞs!',
    //Cookies
    cookies: 'Cookies',
    cookie_policy: 'Politica de Cookie',
    cookies_desc: '¡Usamos Cookies para mejorar tu experiencia! No usamos las cookies para espiඞrte.',
    first_party_cookies: 'Cookies Primarias',
    third_party_cookies: 'Cookies De Terciaraias',
    third_party_cookies_desc: 'Usamos estas cookies en nuestra politicas de servicio:',
    cookie_explanation: 'Te Explicamos',
    locale_cookie_desc: 'Guardamos tu localizacion/lenguaje.',
    color_scheme_cookie_desc: 'El Color de Esquema del Sitio.',
    displaymode_cookie_desc: 'Cambiar la Interfaz de la lista de mods a las siguientes: grilla, tabla, o tabla sin portada.',
    theme_cookie_desc: 'El tema actual del sitio. Luz o Oscuro.',
    allow_cookies_cookie_desc: 'Esta Cookie es necesaria para no preguntarte sobres las cookies otra vez.',
    hidden_announcements_cookie_desc: 'Un registro de ID de publicidad que has decidido ocutlar. Esto previene que vuelva a aparacerer.',
    login_cookies: 'Cookies de Sesion & Ingreso',
    login_cookies_desc: `Usamos multiples cookies para mantenerte ingresado en la pagina y proteger tu cuenta. 
Son necesarias si deseas ingresar en el sitio y mantenerte ingresado.`,
    cookies_allowed_desc: 'Has decidido permitir Cookies. Siempre puedes cambiar de idea.',
    cookies_denied_desc: 'Has rechazado permitir Cookies. Siempre puedes cambiar de idea.',
    cookies_no_choice_desc: 'No eligiste si permitir o no las cookies. La opcion por defecto es no permitirlas.',
    allow_cookies: 'Permitir Cookies',
    disallow_cookies: 'No Permitir Cookies',
    cookies_banner: 'Usamos Cookies 🍪',
    cookies_banner_desc: 'Usamos Cookies para mejorar tu experiencia. ¿Nos permitis guardarlas?'
};